### ISSUE TITLE
Review Master

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/TestBase#1]
Code went straight to master so will need a review

**Comment by rowleya** [comment]
It looks fine; happy if this works (current integration tests are failing though).  We currently have some test support in SupportScripts which includes the github actions code.  Should that code be here too, or is this to be strictly python support?

**Comment by Christian-B** [comment]
"current integration tests are failing though"  that was due to github not accepting urls in the same way for all repositoires.

**Comment by Christian-B** [comment]
" We currently have some test support in SupportScripts which includes the github actions code. Should that code be here too,"

The thinking here is SupportScripts sits below SpinUtils. While TestBase will sit above at Least Front End common so it can include BaseTest case

**Comment by rowleya** [comment]
Not too bothered overall, just trying to see what the thinking was.  The current status is fine anyway, and can always be changed later if desirable.
